using System;
using System.Data;
using System.Configuration;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//--SqlClient for sqlconnection and etc.
using System.Data.SqlClient;
using System.Data.OleDb;
using System.Collections;
using System.IO;
using Microsoft.Office.Core;
using System.Configuration.Assemblies;


public partial class CC_PendingList : System.Web.UI.Page
{
    CCommon con = new CCommon();
    protected void Page_Load(object sender, EventArgs e)
    {
        //if (Session["isView"].ToString() != "1")
        //    Response.Redirect("NoAccess.aspx");
        txtFromDate.Focus();

        if (Session["centreid"].ToString() == "10172")
        {
            btnContact.Visible = true;
        }
        else
        {
            btnContact.Visible = false;
        }
        
    }

    //////////////// protected void btnExport_Click(object sender, EventArgs e)
    ////////////////{
    ////////////////    Response.ClearContent();
    ////////////////    GV1.BackColor = System.Drawing.Color.White;
    ////////////////    GV1.GridLines = GridLines.Both;
    ////////////////    GV1.AutoGenerateDeleteButton = false;
    ////////////////    GV1.AutoGenerateEditButton = false;
    ////////////////    GV1.AllowSorting = false;
    ////////////////    GV1.AllowPaging = false;
    ////////////////    //gvExport.DataBind();

    ////////////////    string attachment = "attachment; filename=PendingReport.xls";

    ////////////////    Table tblSpace = new Table();
    ////////////////    TableRow tblRow = new TableRow();
    ////////////////    TableCell tblCell = new TableCell();
    ////////////////    tblCell.Text = " ";

    ////////////////    TableRow tblRow1 = new TableRow();
    ////////////////    TableCell tblCell1 = new TableCell();
    ////////////////    tblCell1.Text = "<br/><b><font size='4'>PAMAC Finserve Private Limited</font></b> <br/>" +
    ////////////////                     "<b><font size='2'>From Date :</font></b> " + txtFromDate.Text.Trim() + "<br/>" +
    ////////////////                    "<b><font size='2'>To Date :</font></b> " + txtToDate.Text.Trim() + "<br/>";

    ////////////////    tblCell1.CssClass = "label";

    ////////////////    tblRow.Cells.Add(tblCell);
    ////////////////    tblRow1.Cells.Add(tblCell1);

    ////////////////    tblRow.Height = 20;

    ////////////////    tblSpace.Rows.Add(tblRow);
    ////////////////    tblSpace.Rows.Add(tblRow1);

    ////////////////    Response.AddHeader("content-disposition", attachment);

    ////////////////    Response.ContentType = "application/ms-excel";

    ////////////////    StringWriter sw = new System.IO.StringWriter();

    ////////////////    HtmlTextWriter htw = new HtmlTextWriter(sw);
    ////////////////    GV1.EnableViewState = false;
    ////////////////    tblRow1.RenderControl(htw);
    ////////////////    GV1.RenderControl(htw);

    ////////////////    Table tblBottom = new Table();
    ////////////////    TableRow tblRowBottom = new TableRow();
    ////////////////    TableCell tblCellBottom = new TableCell();


    ////////////////    //tblCellBottom.Text = "<br/><b><font size='2'>For&nbsp;</font><font size='4'> PAMAC Finserve Private Limited</font></b><br/><br/><br/>" +
    ////////////////    ////"<b><font size='2'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Authorised Signatory</font></b><br/><br/><br/>" +
    ////////////////    //  "<b><font size='3'>Received By</font></b>";


    ////////////////    tblRowBottom.Cells.Add(tblCellBottom);
    ////////////////    tblRowBottom.Height = 20;

    ////////////////    tblBottom.Rows.Add(tblRowBottom);

    ////////////////    tblRowBottom.RenderControl(htw);

    ////////////////    Response.Write(sw.ToString());

    ////////////////    Response.End();
                 

    ////////////////}
    ////////////////public override void VerifyRenderingInServerForm(Control control)
    ////////////////{

    ////////////////}

    protected void btnReport_Click1(object sender, EventArgs e)
    {
        int iCount = 0;
        try
        {
            bool isValidDates = true;
            if (txtFromDate.Text.Trim() != "" && txtToDate.Text.Trim() != "")
            {
                DateTime dtFrom;
                DateTime dtTo;
                dtFrom = Convert.ToDateTime(con.strDate(txtFromDate.Text.Trim()));
                dtTo = Convert.ToDateTime(con.strDate(txtToDate.Text.Trim()));

                if (dtFrom > dtTo)
                {
                    isValidDates = false;
                    lblMsg.Visible = true;
                    lblMsg.Text = "From date must be less than to date.";
                }
            }
            if (isValidDates == true)
            {
                string sFromDate;
                string sToDate;
                CReport objReport = new CReport();
                DataSet dsPendingList = new DataSet();
                //DataSet dsPendingListHead = new DataSet();

                string Tdate;
                Tdate = Convert.ToDateTime(con.strDate(txtToDate.Text.Trim())).AddDays(1.0).ToString("dd-MMM-yyyy");

                dsPendingList = objReport.GetPendingReportList(con.strDate(txtFromDate.Text.Trim()), Tdate, Session["ClientId"].ToString(), Session["CentreId"].ToString());
                //dsPendingListHead = objReport.GetPendingReportListHead(sFromDate, sToDate, "Pamac Online");

                if (dsPendingList.Tables[0].Rows.Count > 0)
                {

                    ////////GV1.DataSource = dsPendingList;
                    ////////GV1.DataBind();
                    ////////GV1.Visible = true;
                    //--this statement is very important, here the table name should 
                    //--match with the XML Schema table name 
                    dsPendingList.Tables[0].TableName = "PENDINGLIST";


                    //--For Heading of Report------------------

                    //dsPendingListHead.Tables[0].TableName = "PENDINGLISTHEADING";
                    //DataRow drPendingListHead = dsPendingListHead.Tables[0].NewRow();
                    //drPendingListHead["COMPANYNAME"] = "PAMAC Online";
                    //drPendingListHead["FROMDATE"] = txtFromDate.Text.Trim();
                    //drPendingListHead["TODATE"] = txtToDate.Text.Trim();
                    //dsPendingListHead.Tables[0].Rows.Add(drPendingListHead);
                    ///-----------------------------------------------------
                    Session["dataset"] = dsPendingList;

                    //Session["dataset"] = TimeSpan.Zero.Duration().Days;

                    //Session["datasetHead"] = dsPendingListHead;
                    Session["Path"] = Server.MapPath("crPendingList.rpt");
                    Session.Remove("ParameterCollection");
                    iCount = 1;

                    //    Response.Redirect("../../CrystalReportviewer.aspx?bckPgURL=CPV\\CC\\CC_PendingList.aspx");
                    //Response.Redirect("CC_CrystalReportViewer.aspx?bckPgURL=CPV\\CC\\CC_PendingList.aspx");
                }
                else
                {
                    lblMsg.Visible = true;
                    lblMsg.ForeColor = System.Drawing.Color.Red;
                    lblMsg.Text = "No Record found.";
                }
            }
        }
        catch (Exception ex)
        {
            lblMsg.Visible = true;
            lblMsg.ForeColor = System.Drawing.Color.Red;
            lblMsg.Text = "Error :" + ex.Message;
        }
        if (iCount == 1)
        {
           Response.Redirect("../../CrystalReportviewer.aspx?bckPgURL=CPV\\CC\\CC_PendingList.aspx");
        }

        //try catch is added by supriya on 16th Nov2007 
    }

    protected void Button1_Click(object sender, EventArgs e)
    {
        PendingExcelReport();
    }

    public override void VerifyRenderingInServerForm(Control control)
    {

    }

    private void PendingExcelReport()
    {
        try
        {

            string report;

            if (Session["centreid"].ToString() == "10172")
            {
                report = "Sp_PendinglistDubai";
            }
            else
            {
                //report = "Sp_Pendinglist";
                report = "Sp_Pendinglist_Verification";
            }

            CCommon objConn = new CCommon(); SqlConnection sqlcon = new SqlConnection(objConn.AppConnectionString);

            sqlcon.Open();

            SqlCommand CMD2 = new SqlCommand();
            CMD2.Connection = sqlcon;
            CMD2.CommandType = CommandType.StoredProcedure;
            CMD2.CommandText = report;
            CMD2.CommandTimeout = 0;

            SqlParameter FromDate = new SqlParameter();  /// IMP
            FromDate.SqlDbType = SqlDbType.DateTime;
            FromDate.Value = strDate(txtFromDate.Text.Trim());//txtclosingdate.Text.ToString();
            FromDate.ParameterName = "@FromDate";
            CMD2.Parameters.Add(FromDate);

            SqlParameter Todate = new SqlParameter();  /// IMP
            Todate.SqlDbType = SqlDbType.DateTime;
            Todate.Value = strDate(txtToDate.Text.Trim());//txtclosingdate.Text.ToString();
            Todate.ParameterName = "@Todate";
            CMD2.Parameters.Add(Todate);

            SqlParameter Client_ID = new SqlParameter();
            Client_ID.SqlDbType = SqlDbType.VarChar;
            Client_ID.Value = Session["ClientId"].ToString();
            Client_ID.ParameterName = "@Client_ID";
            CMD2.Parameters.Add(Client_ID);

            SqlParameter Centre_id = new SqlParameter();
            Centre_id.SqlDbType = SqlDbType.VarChar;
            Centre_id.Value = Session["CentreId"].ToString();
            Centre_id.ParameterName = "@Centre_id";
            CMD2.Parameters.Add(Centre_id);

            sqlcon.Close();

            SqlDataAdapter Sqlda = new SqlDataAdapter();
            Sqlda.SelectCommand = CMD2;

            DataTable dt = new DataTable();
            Sqlda.Fill(dt);

            GridView1.DataSource = dt;
            GridView1.DataBind();

            string attachment = "attachment; filename=Pending Report.xls";
            Response.ClearContent();
            Response.ClearHeaders();
            Response.Clear();
            Response.AddHeader("content-disposition", attachment);
            Response.ContentType = "application/ms-excel";
            StringWriter sw = new StringWriter();

            HtmlTextWriter htw = new HtmlTextWriter(sw);

            GridView1.RenderControl(htw);
            GridView1.GridLines = System.Web.UI.WebControls.GridLines.Both;
            Response.Write(sw.ToString());
            Response.End(); 
        }
        catch (Exception ex)
        {
          lblMsg.Text = ex.Message;
        }
    }

    private void ContactMIS()
    {
        try
        {        
            
            CCommon objConn = new CCommon(); SqlConnection sqlcon = new SqlConnection(objConn.AppConnectionString);

            sqlcon.Open();

            SqlCommand CMD2 = new SqlCommand();
            CMD2.Connection = sqlcon;
            CMD2.CommandType = CommandType.StoredProcedure;
            CMD2.CommandText = "Sp_Dub_Tele_Contact_MIS";
            CMD2.CommandTimeout = 0;

            SqlParameter FromDate = new SqlParameter();  /// IMP
            FromDate.SqlDbType = SqlDbType.DateTime;
            FromDate.Value = strDate(txtFromDate.Text.Trim());//txtclosingdate.Text.ToString();
            FromDate.ParameterName = "@FromDate";
            CMD2.Parameters.Add(FromDate);

            SqlParameter Todate = new SqlParameter();  /// IMP
            Todate.SqlDbType = SqlDbType.DateTime;
            Todate.Value = strDate(txtToDate.Text.Trim());//txtclosingdate.Text.ToString();
            Todate.ParameterName = "@Todate";
            CMD2.Parameters.Add(Todate);

            SqlParameter Client_ID = new SqlParameter();
            Client_ID.SqlDbType = SqlDbType.VarChar;
            Client_ID.Value = Session["ClientId"].ToString();
            Client_ID.ParameterName = "@Client_ID";
            CMD2.Parameters.Add(Client_ID);

            SqlParameter Centre_id = new SqlParameter();
            Centre_id.SqlDbType = SqlDbType.VarChar;
            Centre_id.Value = Session["CentreId"].ToString();
            Centre_id.ParameterName = "@Centre_id";
            CMD2.Parameters.Add(Centre_id);

            sqlcon.Close();

            SqlDataAdapter Sqlda = new SqlDataAdapter();
            Sqlda.SelectCommand = CMD2;

            DataTable dt = new DataTable();
            Sqlda.Fill(dt);

            GridView1.DataSource = dt;
            GridView1.DataBind();

            string attachment = "attachment; filename=Count Report.xls";
            Response.ClearContent();
            Response.ClearHeaders();
            Response.Clear();
            Response.AddHeader("content-disposition", attachment);
            Response.ContentType = "application/ms-excel";
            StringWriter sw = new StringWriter();

            HtmlTextWriter htw = new HtmlTextWriter(sw);

            GridView1.RenderControl(htw);
            GridView1.GridLines = System.Web.UI.WebControls.GridLines.Both;
            Response.Write(sw.ToString());
            Response.End();
        }
        catch (Exception ex)
        {
            lblMsg.Text = ex.Message;
        }
    }

    public string strDate(string strInDate)
    {
        string strDD = strInDate.Substring(0, 2);

        string strMM = strInDate.Substring(3, 2);

        string strYYYY = strInDate.Substring(6, 4);

        string strMMDDYYYY = strMM + "/" + strDD + "/" + strYYYY;  //on Server 

        //string strMMDDYYYY = strDD + "/" + strMM + "/" + strYYYY;   //On local machine

        DateTime dtConvertDate = Convert.ToDateTime(strMMDDYYYY);

        string strOutDate = dtConvertDate.ToString("dd-MMM-yyyy");

        return strOutDate;
    }
    
    protected void btnContact_Click(object sender, EventArgs e)
    {
        ContactMIS();
    }
}
