using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Data.OleDb;
using System.Text;
using System.IO;
using Microsoft.Office.Core;
using System.Configuration.Assemblies;
using CrystalDecisions.Shared;


public partial class CPV_CC_TcWiseSearch : System.Web.UI.Page
{
    sup_remarks objq = new sup_remarks();
    CCommon objcon = new CCommon();
    DateTime dtfrom;
    DateTime dtto;
    
    protected void Page_Load(object sender, EventArgs e)
    {
        CCommon objConn = new CCommon();
        sdsCenter.ConnectionString = objConn.ConnectionString;  //Sir

        if (!IsPostBack)
        {

        }
    }
    private void propertyset()
    {
       
        objq.centreid = Session["CentreID"].ToString();
        objq.clientid = Session["Clientid"].ToString();
    }
   


    private struct Gridposition
    {
        public const int caseid = 0;
        public const int CompanyName = 1;
        public const int Date = 2;
        public const int RT = 3;
        public const int BT = 4;
        public const int Total = 5;
    }
    protected void btnsearch_Click(object sender, EventArgs e)
    {
        bool isvaliddate = true;
            if (txtFDate.Text.Trim() =="" || txtTDate.Text.Trim() == "")
            {
                isvaliddate = false;
                lblMessage.Visible = true;
                lblMessage.Text = "Please Enter From Date And To Date";
                lblMessage.ForeColor = System.Drawing.Color.Red;
                lblMessage.Font.Bold = true;
            }
            if (txtFDate.Text.Trim() != "" && txtTDate.Text.Trim() != "")
            {
                dtfrom = Convert.ToDateTime(objcon.strDate(txtFDate.Text.Trim()));
                dtto = Convert.ToDateTime(objcon.strDate(txtTDate.Text.Trim()));

                if (dtfrom > dtto)
                {
                    isvaliddate = false;
                    lblMessage.Visible = true;
                    lblMessage.Text = "From Date must be less than To Date";
                }
            }
            if (isvaliddate == true)
            {
                lblMessage.Text = "";
            }

        
    
        string qry = "";
        //DateTime frdate;
        //DateTime todate;
        
        //frdate = Convert.ToDateTime(objcon.strDate(txtFDate.Text.Trim()));
        //todate = Convert.ToDateTime(objcon.strDate(txtTDate.Text.Trim()));

        qry = "exec TcWiseReport_centreDcr '" + Convert.ToDateTime(objcon.strDate(txtFDate.Text.Trim())).ToString("dd-MMM-yyyy") + "','" + Convert.ToDateTime(objcon.strDate(txtTDate.Text.Trim())).ToString("dd-MMM-yyyy") + "','" + Session["ClientId"].ToString() + "','" + ddlCenter.SelectedValue.ToString() + "'";
        OleDbDataAdapter oledba = new OleDbDataAdapter(qry,objcon.ConnectionString );
        DataSet ds = new DataSet();
        DataTable dt = new DataTable();
        oledba.Fill(ds, "TcWiseReport_centre");
        dt = ds.Tables["TcWiseReport_centre"];

        gvtc.DataSource = dt;
        gvtc.DataBind();
       
    }
    protected void btnExport_Click(object sender, EventArgs e)
    {

        Response.ClearContent();
        gvtc.BackColor = System.Drawing.Color.White;
        gvtc.GridLines = System.Web.UI.WebControls.GridLines.Both;
        gvtc.AutoGenerateDeleteButton = false;
        gvtc.AutoGenerateEditButton = false;
        gvtc.AllowSorting = false;
        gvtc.AllowPaging = false;
        //gvExport.DataBind();

        string attachment = "attachment; filename=TcAssignedCasesQueue.xls";

        Table tblSpace = new Table();
        TableRow tblRow = new TableRow();
        TableCell tblCell = new TableCell();
        tblCell.Text = " ";

        TableRow tblRow1 = new TableRow();
        TableCell tblCell1 = new TableCell();
        tblCell1.Text = "<br/><b><font size='4'>PAMAC Finserve Private Limited</font></b> <br/>" +
                         "<b><font size='2'>From Date :</font></b> " + txtFDate.Text.Trim() + "<br/>";
        //"<b><font size='2'>To Date :</font></b> " + txtToDate.Text.Trim() + "<br/>";

        tblCell1.CssClass = "label";

        tblRow.Cells.Add(tblCell);
        tblRow1.Cells.Add(tblCell1);

        tblRow.Height = 20;

        tblSpace.Rows.Add(tblRow);
        tblSpace.Rows.Add(tblRow1);


        Response.AddHeader("content-disposition", attachment);

        Response.ContentType = "application/ms-excel";

        StringWriter sw = new System.IO.StringWriter();

        HtmlTextWriter htw = new HtmlTextWriter(sw);
        gvtc.EnableViewState = false;
        tblRow1.RenderControl(htw);
        gvtc.RenderControl(htw);

        Table tblBottom = new Table();
        TableRow tblRowBottom = new TableRow();
        TableCell tblCellBottom = new TableCell();


        //tblCellBottom.Text = "<br/><b><font size='2'>For&nbsp;</font><font size='4'> PAMAC Finserve Private Limited</font></b><br/><br/><br/>" +
        ////"<b><font size='2'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Authorised Signatory</font></b><br/><br/><br/>" +
        //  "<b><font size='3'>Received By</font></b>";


        tblRowBottom.Cells.Add(tblCellBottom);
        tblRowBottom.Height = 20;

        tblBottom.Rows.Add(tblRowBottom);

        tblRowBottom.RenderControl(htw);

        Response.Write(sw.ToString());

        Response.End();

    }
    public override void VerifyRenderingInServerForm(Control control)
    {
        
    }
}
