using System;
using System.Data;
using System.Configuration;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//--SqlClient for SqlConnection and etc.
using System.Data.SqlClient;
using System.Data.OleDb;
using System.Collections;
using System.IO;
using Microsoft.Office.Core;
using System.Configuration.Assemblies;


public partial class CC_PendingList : System.Web.UI.Page
{
    CCommon con = new CCommon();
    protected void Page_Load(object sender, EventArgs e)
    {
        //if (Session["isView"].ToString() != "1")
        //    Response.Redirect("NoAccess.aspx");
        txtFromDate.Focus();       
    }

    //////////////// protected void btnExport_Click(object sender, EventArgs e)
    ////////////////{
    ////////////////    Response.ClearContent();
    ////////////////    GV1.BackColor = System.Drawing.Color.White;
    ////////////////    GV1.GridLines = GridLines.Both;
    ////////////////    GV1.AutoGenerateDeleteButton = false;
    ////////////////    GV1.AutoGenerateEditButton = false;
    ////////////////    GV1.AllowSorting = false;
    ////////////////    GV1.AllowPaging = false;
    ////////////////    //gvExport.DataBind();

    ////////////////    string attachment = "attachment; filename=PendingReport.xls";

    ////////////////    Table tblSpace = new Table();
    ////////////////    TableRow tblRow = new TableRow();
    ////////////////    TableCell tblCell = new TableCell();
    ////////////////    tblCell.Text = " ";

    ////////////////    TableRow tblRow1 = new TableRow();
    ////////////////    TableCell tblCell1 = new TableCell();
    ////////////////    tblCell1.Text = "<br/><b><font size='4'>PAMAC Finserve Private Limited</font></b> <br/>" +
    ////////////////                     "<b><font size='2'>From Date :</font></b> " + txtFromDate.Text.Trim() + "<br/>" +
    ////////////////                    "<b><font size='2'>To Date :</font></b> " + txtToDate.Text.Trim() + "<br/>";

    ////////////////    tblCell1.CssClass = "label";

    ////////////////    tblRow.Cells.Add(tblCell);
    ////////////////    tblRow1.Cells.Add(tblCell1);

    ////////////////    tblRow.Height = 20;

    ////////////////    tblSpace.Rows.Add(tblRow);
    ////////////////    tblSpace.Rows.Add(tblRow1);

    ////////////////    Response.AddHeader("content-disposition", attachment);

    ////////////////    Response.ContentType = "application/ms-excel";

    ////////////////    StringWriter sw = new System.IO.StringWriter();

    ////////////////    HtmlTextWriter htw = new HtmlTextWriter(sw);
    ////////////////    GV1.EnableViewState = false;
    ////////////////    tblRow1.RenderControl(htw);
    ////////////////    GV1.RenderControl(htw);

    ////////////////    Table tblBottom = new Table();
    ////////////////    TableRow tblRowBottom = new TableRow();
    ////////////////    TableCell tblCellBottom = new TableCell();


    ////////////////    //tblCellBottom.Text = "<br/><b><font size='2'>For&nbsp;</font><font size='4'> PAMAC Finserve Private Limited</font></b><br/><br/><br/>" +
    ////////////////    ////"<b><font size='2'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Authorised Signatory</font></b><br/><br/><br/>" +
    ////////////////    //  "<b><font size='3'>Received By</font></b>";


    ////////////////    tblRowBottom.Cells.Add(tblCellBottom);
    ////////////////    tblRowBottom.Height = 20;

    ////////////////    tblBottom.Rows.Add(tblRowBottom);

    ////////////////    tblRowBottom.RenderControl(htw);

    ////////////////    Response.Write(sw.ToString());

    ////////////////    Response.End();
                 

    ////////////////}
    ////////////////public override void VerifyRenderingInServerForm(Control control)
    ////////////////{

    ////////////////}

    protected void btnReport_Click1(object sender, EventArgs e)
    {
        int iCount = 0;
        try
        {
            bool isValidDates = true;
            if (txtFromDate.Text.Trim() != "" && txtToDate.Text.Trim() != "")
            {
                DateTime dtFrom;
                DateTime dtTo;
                dtFrom = Convert.ToDateTime(con.strDate(txtFromDate.Text.Trim()));
                dtTo = Convert.ToDateTime(con.strDate(txtToDate.Text.Trim()));

                if (dtFrom > dtTo)
                {
                    isValidDates = false;
                    lblMsg.Visible = true;
                    lblMsg.Text = "From date must be less than to date.";
                }
            }
            if (isValidDates == true)
            {
                string sFromDate;
                string sToDate;
                CReport objReport = new CReport();
                DataSet dsPendingList = new DataSet();
                //DataSet dsPendingListHead = new DataSet();

                string Tdate;
                Tdate = Convert.ToDateTime(con.strDate(txtToDate.Text.Trim())).AddDays(1.0).ToString("dd-MMM-yyyy");

                dsPendingList = objReport.GetPendingReportList(con.strDate(txtFromDate.Text.Trim()), Tdate, Session["ClientId"].ToString(), Session["CentreId"].ToString());
                //dsPendingListHead = objReport.GetPendingReportListHead(sFromDate, sToDate, "Pamac Online");

                if (dsPendingList.Tables[0].Rows.Count > 0)
                {

                    ////////GV1.DataSource = dsPendingList;
                    ////////GV1.DataBind();
                    ////////GV1.Visible = true;
                    //--this statement is very important, here the table name should 
                    //--match with the XML Schema table name 
                    dsPendingList.Tables[0].TableName = "PENDINGLIST";


                    //--For Heading of Report------------------

                    //dsPendingListHead.Tables[0].TableName = "PENDINGLISTHEADING";
                    //DataRow drPendingListHead = dsPendingListHead.Tables[0].NewRow();
                    //drPendingListHead["COMPANYNAME"] = "PAMAC Online";
                    //drPendingListHead["FROMDATE"] = txtFromDate.Text.Trim();
                    //drPendingListHead["TODATE"] = txtToDate.Text.Trim();
                    //dsPendingListHead.Tables[0].Rows.Add(drPendingListHead);
                    ///-----------------------------------------------------
                    Session["dataset"] = dsPendingList;

                    //Session["datasetHead"] = dsPendingListHead;
                    Session["Path"] = Server.MapPath("crPendingList.rpt");
                    Session.Remove("ParameterCollection");
                    iCount = 1;

                    //    Response.Redirect("../../CrystalReportviewer.aspx?bckPgURL=CPV\\CC\\CC_PendingList.aspx");
                    //Response.Redirect("CC_CrystalReportViewer.aspx?bckPgURL=CPV\\CC\\CC_PendingList.aspx");
                }
                else
                {
                    lblMsg.Visible = true;
                    lblMsg.ForeColor = System.Drawing.Color.Red;
                    lblMsg.Text = "No Record found.";
                }
            }
        }
        catch (Exception ex)
        {
            lblMsg.Visible = true;
            lblMsg.ForeColor = System.Drawing.Color.Red;
            lblMsg.Text = "Error :" + ex.Message;
        }
        if (iCount == 1)
        {
           Response.Redirect("../../CrystalReportviewer.aspx?bckPgURL=CPV\\CC\\CC_PendingList.aspx");
        }

        //try catch is added by supriya on 16th Nov2007 
    }
}
